import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Portsite Generated Site",
  description: "Generated by Portsite",

  icons: {
    icon: "/assets/favicon.ico",
    shortcut: "/assets/favicon.ico",
    apple: "/apple-touch-icon.png",
  },

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <div className="fixed bottom-4 right-4 z-50">
          <a 
            href="https://portfoliowebsite.ai" 
            target="_blank" 
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1.5 px-3 py-2 text-xs font-medium text-white bg-black/90 backdrop-blur-md rounded-full shadow-2xl border border-white/10 hover:bg-black hover:scale-105 transition-all duration-300 hover:shadow-white/20"
          >
            <span className="opacity-80">Made with</span>
            <span className="font-bold bg-gradient-to-r from-gray-400 to-gray-600 bg-clip-text text-transparent">Portsite</span>
            
          </a>
        </div>
      </body>
    </html>
  );
}
